platform :osx, '10.9'

use_frameworks!

target 'Unbound' do
  pod 'Fabric'
  pod 'Crashlytics'

  target 'Unbound Trial' do
    pod 'DevMateKit', '~>1.7'
    pod 'Sparkle', '~>1.13.1'
  end
  
  target 'Unbound Non-Sandbox'
  
end
